services:
  dataportal-ui:
    image: ghcr.io/medizininformatik-initiative/feasibility-gui:pr-499
    restart: unless-stopped
    volumes:
      - ./deploy-config.json:/usr/share/nginx/html/assets/config/config.deploy.json
