services:
  dataportal-ui:
    image: ghcr.io/medizininformatik-initiative/dataportal-ui:6.6.0
    restart: unless-stopped
    volumes:
      - ./deploy-config.json:/usr/share/nginx/html/assets/config/config.deploy.json
